version: "3"
services:
  accomodation_db:
    image: postgres:13
    restart: always
    networks:
      - servers
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: AccomodationServiceDB
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      retries: 3
      interval: 5s
      timeout: 5s
    container_name: accomodation_db
    volumes:
      - accomodation-data:/var/lib/postgresql/data

  accomodation-service:
    build: .
    restart: on-failure
    networks:
      - servers
    container_name: accomodation-service
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
    ports:
      - "8082:8082"
    depends_on:
      accomodation_db:
        condition: service_healthy

volumes:
  accomodation-data:

networks:
  servers:
    external: true
