version: "3"

x-logging: &fluent-bit
    driver: fluentd
    options:
        fluentd-address:  172.18.0.9:24224

services:
  accomodation_db:
    image: postgres:13
    restart: always
    networks:
      - servers
      - monitoring
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: AccomodationServiceDB
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      retries: 3
      interval: 5s
      timeout: 5s
    container_name: accomodation_db
    volumes:
      - accomodation-data:/var/lib/postgresql/data
    logging: *fluent-bit
    

  accomodation-service:
    build: .
    restart: on-failure
    networks:
      - servers
      - monitoring
    container_name: accomodation-service
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: root
      DATABASE_HOST: accomodation_db
      SERVICE_PATH:  0.0.0.0:8082
      JAEGER_SERVICE_NAME: accomodation-service
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 6831
      JAEGER_SAMPLER_MANAGER_HOST_PORT: jaeger:5778
      JAEGER_SAMPLER_TYPE: const
      JAEGER_SAMPLER_PARAM: 1
    ports:
      - "8082:8082"
    logging: *fluent-bit
    depends_on:
      accomodation_db:
        condition: service_healthy
    volumes:
      - ./images:/app/images

volumes:
  accomodation-data:

networks:
  servers:
    external: true
  monitoring:
    external: true
